---
version: "3.3"
services:
  app:
    build: .
    # image: easilok/mark-notes-server
    image: docker.luispereira.xyz/mark-notes-server
    container_name: mark-notes-server
    environment:
      - EXAMPLE=''
    volumes:
      - "./notes:/notes"
    ports:
      - 8080:8080
    # restart: always
