---
version: "3.3"
services:
  app:
    build: .
    image: easilok/mark-notes-server
    container_name: mark-notes-server
    environment:
      - MONGODB_URI=''
    volumes:
      - "./media:/media"
    ports:
      - 8080:8080
    # restart: always
